### ISSUE TITLE
Crashes when switching content

### ISSUE THREAD

**Issue by alfrix** [libretro/dolphin#11]
1. load a rom, let it run a bit
2. open the menu
3. load another without closing the running one
High chances of a crash.
Switching between GC/WII makes things worse

**Comment by andres-asm** [comment]
I think this was likely on the old core, please try to confirm and close if no longer relevant

**Comment by alfrix** [comment]
This it's still an issue

**Comment by Papermanzero** [comment]
Cannot reproduce the issue

**Comment by alfrix** [comment]
Outdated
