### ISSUE TITLE
Dolphin will only stream to a black screen now (with audio)

### ISSUE THREAD

**Issue by klepp0906** [libretro/dolphin#113]
So i havent used the dolphin core in a minute.   I used to play baiten kratos and twilight princess with it from bed/streaming over steam.

Well, I tried to return to twilight princess today and got a black screen with audio playing.   I could still go in and out of the RA menu, but no gameplay on my tv (or if i looked at my pc I was streaming from, screen was black as well).  Not an RA issue as I have no problem with any other cores, and I switched RA versions to eliminate the easy stuff first ;p

If launched at my pc.  Works.  If launched at my pc through steam, still works.   Only stops working if launched through steam from my tv/streaming.

Swapping video driver to D3D works around the issue at a cost of course, or id be using d3d in the first place. 

Seems the problem lay with OGL and streaming.   

I did try different nvidia drivers with no luck.

**Comment by klepp0906** [comment]
So after some more testing.  It seems it launches properly via a command line shortcut in steam.  Every time, without fail.

for some reason it takes substantially longer to load this way, but the game eventually appears, whereas launched from RA, it does not.

hopefully this can help narrow it down

**Comment by hectik17** [comment]
change the video mode from gl to Vulkun, worked for me, having black screen issues.
would you happen to know how to get the anolog trigers working? for half press on games liek SMsunshine?

**Comment by klepp0906** [comment]
i wish that worked for me.  unfortunately the steam link app has never streamed anything vulkan.  no vulkan backends, no native vulkan windows games.   Valve has known about it for a long time so who knows.  People QQ'ing about it all the way back to the Doom2016 release.

ive used D3D or GL this entire time.  (overwhelmingly GL).

Theres the thing that it was never an issue prior.   Also the issue that GL works fine with other cores so no idea what differentiates current dolphin.   I think it may be a frontend thing though potentially.  Above my paygrade.

As for triggers, i have no idea about half presses.  Maybe mapping within the steam controller configurator is all i can think of.  Ive never played a game that required it thus never tried unfortunately.

**Comment by hectik17** [comment]
Ahh well I use to have a problem with CS1.6 black screen I just changed some seting in nvidia. Here is a guide I wrote up at the time to fix it let me know if this resolves the black screen
https://steamcommunity.com/sharedfiles/filedetails/?id=1583449692

**Comment by klepp0906** [comment]
Huh, that’s one of those things I’d never consider being related but willing to give it a try. At the gym atm but will give it a shake later.  Thanks :)

**Comment by klepp0906** [comment]
what fixed it for me is going to buffer flipping mode and forcing blit on
![image](https://user-images.githubusercontent.com/10392920/66827659-25df6c00-ef1d-11e9-93ee-e32081eb3f29.png)
no more black screen regardless of backend and vulkan streams fine.

**Comment by hectik17** [comment]
Good to hear. I also fixed half press trigger buttons in retroarch dolphin using PS3 controll. Not sure how tho. Got it working prefect for super mario sunshine

Somehow was able to choose device type: GameCube controller and swapped the r1 r2 button maps around I'm retroarch. I am also using scpdrivers and steam  controller mapping. That's some lead to as what I did. It was all trial and error and I can't only replicate it only buy copying the whole retroarch folder

**Comment by klepp0906** [comment]
huh, thats the worst when you cant replicate something lol.  At least its working though.  Sounds like yesterday was a good day for everyone:P

now i just have to find out why my RA wont do legitimate fullscreen exclusive, no matter what I have it set to, it functions as borderless windowed.

sometimes i spend more time fixing it, than actually using it.  good times :)
