### ISSUE TITLE
Core provided aspect ratio in wii games doesn't fill the screen.

### ISSUE THREAD

**Issue by i30817** [libretro/dolphin#14]
What i think happens typically (correct me if i'm wrong) with 'video->aspect ratio = Core provided' cores in fullscreen is enlarging the the 'core provided' aspect ratio at the same fractional multiplier for both width and height until one of width or height equals the fullscreen width or height and leave either black columns (if heights touched first) or black rows (if width touched first).

This seems to work fine for the dolphin core for Gamecube games, but for Wii games it causes both black columns and black rows.

Standalone upstream dolphin (or the libretro-dolphin-launcher, which unfortunately doesn't work in KMS environments) doesn't do this. Maybe the core needs to be divided into two like mednafen_psx and mednafen_saturn etc?

16:9 'fills' the screen width for Wii games here (1366x768) but it's distorting the image (it's stretching the width but keeping the height).

**Comment by alfrix** [comment]
Not happening anymore on the newer builds

**Comment by i30817** [comment]
It's still happening though. Just install the 'dolphin launcher core' (and dolphin) and the 'dolphin core' in linux and start Resident Evil Archives in both cores. The upstream dolphin core/launcher fills the screen without stretch as far as it can. The RA core letterboxes the whole intro and the main menu.

**Comment by i30817** [comment]
though on second thought this may be because the ppa wasn't updated to the 'last' version. It's a freaking pain to download the 'last' buildbot version on linux and it might not even work because of non-static linking (there is a issue about that here...), but i can try after uninstalling the ppa version.

**Comment by i30817** [comment]
That's sort of confirmed. The dolphin launcher core is slightly wider horizontally for some reason but both now fill the vertical space.

And i'm further annoyed at how outdated the ppa is.

**Comment by i30817** [comment]
Actually never mind the 'width', i simply didn't figure out that i hadn't the 'aspect ratio' on the main graphics options (not core) not set to core provided. Closed i guess.
