### ISSUE TITLE
cannot use libretro core without manually downloading assets

### ISSUE THREAD

**Issue by soredake** [libretro/dolphin#143]
see https://github.com/libretro/docs/blob/master/docs/library/dolphin.md#setup

**Comment by soredake** [comment]
https://github.com/libretro/retroarch-assets/issues/356

**Comment by ischorr** [comment]
Strangely, I seem to be using the Dolphin core fine without a copy of the Sys folder - is this just out of date?

Edit:  Ah, in my case the assets are in [retroarch]/saves/dolphin-emu/User, not [retroarch]/System/dolphin-emu/Sys
