### ISSUE TITLE
Sideways Wiimote configuration has incorrect mapping and can't be corrected via UI

### ISSUE THREAD

**Issue by kaosushijin** [libretro/dolphin#162]
The following forum post describes the issue:

https://forums.libretro.com/t/remapping-wiimote-sideways-controls-in-dolphin-core/26093

In the Sideways WiiMote configuration, 1 and 2 should map to XInput "A" and "B" respectively, but they end up being attached to "Y" and "X" respectively instead.  This can't be corrected by changing the input configuration because the dolphin core is not respecting the input configuration.

The workaround is to manually remap the standard WiiMote controller configuration to match a sideways use case.

**Comment by medievil1** [comment]
seems to work fine here (though I was using a 360 controller as sideways wiimote... had to fix the u/d l/r config but 1,2 are definitely retropad a/b (right most button and bottom button)

**Comment by kaosushijin** [comment]
Tested this recently and it works as desired.  Must have been fixed over time.
