### ISSUE TITLE
Analog Shoulder Buttons in Gamecube Mode

### ISSUE THREAD

**Issue by Papermanzero** [libretro/dolphin#177]
The analog shoulder buttons do not work. It seems the latest changes deleted the controller options. So all the settings for analog shoulder buttons are gone.

**Comment by Mr-Jake** [comment]
I think this pull request should fix it. We just have to wait for it to be approved.

https://github.com/libretro/dolphin/pull/166

**Comment by Papermanzero** [comment]
Yes, indeed. It depends how the PR implements the feature.

**Comment by Papermanzero** [comment]
Any update on this one? Several games like mario sunshine are not playable anymore. We resolved that problem with a PR some years ago. Now it is broken again... 😔

**Comment by rods012** [comment]
This continues to be a major issue with games that rely on the analog triggers, any news on if it is being addressed?

**Comment by Papermanzero** [comment]
The whole dolphin emulator is neglected.
It would be really great to add the features which the standalone offers. Analog Triggers are a must for certain cube games

**Comment by Darkhost1999** [comment]
It's sad the old dolphin core that was pinned became unpinned in the discord.
Because analog has worked in the past. But now Mario Sunshine is not able to be completed.

**Comment by Papermanzero** [comment]
it is working with the latest updates

**Comment by Papermanzero** [comment]
fixed
