### ISSUE TITLE
Disc append not working.

### ISSUE THREAD

**Issue by bslenul** [libretro/dolphin#182]
Hey!

It seems like disc swapping is broken, when trying to append disc (no other choice since the core doesn't support .m3u) you get an error "Failed to append disc":

![image](https://user-images.githubusercontent.com/33353403/100489830-21711500-3117-11eb-9ac2-30d051ff0531.png)

Nothing about the error in logs, just the notification. Also ejecting doesn't seem to do anything, with other cores when you click "Eject Disc" it changes to "Insert Disc" and a new "Current Disc Index" option appears (even if you loaded a single disc), like this:

![image](https://user-images.githubusercontent.com/33353403/100489889-8a588d00-3117-11eb-989c-2166a16e9ac5.png)

But with Dolphin it stays to "Eject Disc" and the "Current Disc Index" never appears.

Happening on both Windows 10 and my Linux Mint VM, I wanted to bisect but I can't find a version of the core where it's working, even with c9cb09c it doesn't, and it was the first commit to implement disc swapping... So maybe it's some kind of conflict between the core and the changes that happened to disc control menu a while ago (https://github.com/libretro/RetroArch/pull/10003)? I could try tomorrow with a RetroArch version before these changes.

**Comment by bslenul** [comment]
> I could try tomorrow with a RetroArch version before these changes.

OK so I tried with a RetroArch version prior to that PR I mentioned, and it worked... kinda. So I booted disc 2 of Killer 7 and started a new game then when it asked for disc 1 I went to the disc control menu and there's already an issue:

![image](https://user-images.githubusercontent.com/33353403/100515620-b6a6f480-317d-11eb-9022-adcc4a013d72.png)

The disc index is set to "null" instead of "1", then because of this when I append disc 1 it just replaces current disc with disc 1 instead of... well, appending it :p 

![image](https://user-images.githubusercontent.com/33353403/100515647-eeae3780-317d-11eb-9463-7492e0430614.png)

The disc loaded properly but it didn't "append", it should say "Setting disk in tray: 2/2.", not "1/1"! MGS with Beetle PSX HW as an example:

![image](https://user-images.githubusercontent.com/33353403/100515831-31244400-317f-11eb-9725-fe77e2f04d66.png)

Also the cycle tray status option doesn't seem to work properly, so even if you append 2 discs properly you can never switch disc index.

So IMO (not a dev, I could be completely wrong...), disc index being "null" creates issues with disc swapping in recent RA versions, or at least it might be one of the causes.

**Comment by Gophberg** [comment]
I confirm this.
Retroarch v1.7.6 with Dolphin v5.0 extract the first disc and append the second disc properly.
But Retroarch v1.9.0 can't that.
