### ISSUE TITLE
Mario Party 4: game crashes retroarch after cinematic

### ISSUE THREAD

**Issue by legluondunet** [libretro/dolphin#19]
Hello,

Mario Party 4 gamecube game crashes Retroarch after cinematic, the screen is all grey then Retroarch freezes.
I can not reproduce this bug with last Dolphin revision and on the compatibility list, this game should run without any problem:
https://wiki.dolphin-emu.org/index.php?title=Mario_Party_4

Thank you for your help.

infos:
Mario Party 4 EU\md5sum : f6740fc00d9818ad1f161889382c7902
Ubuntu 18.04

**Comment by inactive123** [comment]
Can you retry this again with the latest core?

**Comment by legluondunet** [comment]
I just tried and I obtained this error message:

$ ./retroarch  -L ~/.config/retroarch/cores/dolphin_libretro.so 'Mario Party 4 (Europe) (En,Fr,De,Es,It) (v1.02).iso' 
[INFO] RetroArch 1.7.3 (Git 39a1e494c5)
[INFO] Redirection de la sauvegarde instantanée vers "/home/legluondunet/.config/retroarch/savefiles/Mario Party 4 (Europe) (En,Fr,De,Es,It) (v1.02).srm".
[INFO] Redirection de la sauvegarde instantanée vers "/home/legluondunet/.config/retroarch/savestates/Mario Party 4 (Europe) (En,Fr,De,Es,It) (v1.02).state".
[INFO] === Build =======================================
Capacités: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Jul  1 2018
[INFO] Version: 1.7.3
[INFO] Git: 39a1e494c5
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/home/legluondunet/.config/retroarch/cores/dolphin_libretro.so"
[ERROR] Failed to open libretro core: "/home/legluondunet/.config/retroarch/cores/dolphin_libretro.so"
[ERROR] Error(s): libavformat-ffmpeg.so.56: cannot open shared object file: No such file or directory
Erreur de segmentation (core dumped)

**Comment by legluondunet** [comment]
I compiled last Libretro Dolphin core git sources instead of downloaded it with Retroarch to avoid bad dependencies. The core loaded without error and I tested Mario Party 4: no more crash.

Thank you for your help.
