### ISSUE TITLE
Please, reduce the insane spam in log

### ISSUE THREAD

**Issue by bslenul** [libretro/dolphin#194]
Hey, forgot about this because I changed "Log Level" to "Warning" a while ago but currently the amount of spam the core throws in logs is insane, here's an example: https://pastebin.com/pR1GbAiw

This is just by starting TimeSplitters (but it's the same with any game) and exiting after the loading screen. Soooo many duplicated lines, and at least on Windows it's pretty bad because if you have the console log window opened, it delays the start and exit of the core (I guess it waits until everything is printed?), example with Metroid Prime:

* With log level to "Info" (~6sec to start):

https://user-images.githubusercontent.com/33353403/109950243-9aff3d00-7cdc-11eb-956b-8265e7e73f31.mp4

* With log level to "Warning" (~3sec to start):

https://user-images.githubusercontent.com/33353403/109950272-a2264b00-7cdc-11eb-9e86-af5aa0135b48.mp4

**Comment by inactive123** [comment]
Sure, I'm not a fan of the log spam either. Can you point us to a commit where this was not yet such a big issue?

**Comment by bslenul** [comment]
Hm I have this set to "Warning" for a long time now, the oldest version I have right now is 1fbd599 (october 2019) and it was already spamming 😓 but I'll see if I can compile even older builds.

**edit:** Tried dcd53adc339b59ab36fcbbc4dab7fc28e43892c4 and it was already spamming (December 2018!) :/
