### ISSUE TITLE
Deadlock on startup

### ISSUE THREAD

**Issue by alice-mkh** [libretro/dolphin#196]
DolphinAnalytics() reloads config, which wants to pause the game. We do it while the game is running a frame, meaning it will wait forever.

This can be worked around by commenting out the contents of `DolphinAnalytics::ReloadConfig()`, but that will break actual analytics.

However, I wonder if they should be enabled in the libretro core. They are supposed to be opt-in in standalone Dolphin, but as far as I can see they aren't in the core.

**Comment by inactive123** [comment]
Yeah, we don't want any analytics in the libretro port whatsoever.
