### ISSUE TITLE
Feature Request: Proper implementation of UberShaders

### ISSUE THREAD

**Issue by ghost** [libretro/dolphin#213]
The core settings deceptively have the UberShader compilation options available in the Shader Compilation setting, however, these options fail to do anything to combat the stuttering issues Dolphin is quite known for. If UberShaders were properly implemented, it could improve the performance of the core by a substantial margin. So with that said, would it be possible to have UberShaders properly implemented in the core? 

Thanks for reading.

**Comment by danprice142** [comment]
I am hoping for this too
