### ISSUE TITLE
[gamecube] second gamepad not automatically detected

### ISSUE THREAD

**Issue by legluondunet** [libretro/dolphin#25]
Hello,

I have two x360 gamepad connected to my computer and Retroarch recognized them automatically available with N64, Reicast, Beetle PCSX...cores.
But not with Dolphin Gamecube: only one gamepad is available, is it a known bug?

**Comment by gouchi** [comment]
Hi,

Did you enable second controller  ? By going to the Dolphin.ini in savefiles/Config/Dolphin/ and duplicate the first controller entry.

SIDevice0 = 6
SIDevice1 = 6

[Source](https://forums.libretro.com/t/solved-dolphin-gamecube-2-players/13686/4)

Thank you.

**Comment by legluondunet** [comment]
Hello Gouchi, nice workaround, works very well, my two gamepads are now active and I can finally play a versus on Mario Kart game.
I think the Dolphin libretro core should integrate this workaround or this functionnality like others cores: the gamepad is automatically managed by retroarch and the core, you don't have to edit config files to add one or more gamepad.

**Comment by hadim** [comment]
I confirm it works perfectly with this hack. You definitively want to integrate this somewhere in the core or in libretro.

**Comment by Harpy1991** [comment]
Mine wont detect even the first controler. in all other games i can use my xbox360 controller. no problem but in dolphin core it does not work

**Comment by Papermanzero** [comment]
You need a setting possibility in the core options which writes the correct values in the dolphin ini.

**Comment by Papermanzero** [comment]
https://github.com/libretro/dolphin/issues/47

**Comment by flyinghead** [comment]
This should be fixed as of 1a7d1bc867e62f85598e79ed8d704259869c773e

**Comment by legluondunet** [comment]
I just tested, deleted my old Dolphin libretro core config, started Mario Kart and my two gamepad worked. I saw you enabled now 4 controllers by default in dolphin.ini.
Thank you.
