### ISSUE TITLE
(Feature Request) Prefetch custom textures

### ISSUE THREAD

**Issue by twoprimehydroxyl** [libretro/dolphin#273]
Is there any way to incorporate the "Prefetch Custom Textures" option from the standalone Dolphin emulator?

**Comment by bslenul** [comment]
Added: https://github.com/libretro/dolphin/pull/274
Just have to wait until the PR is accepted then it should be available on the core downloader a few hours later.

As mentioned in the PR, depending on the size of the textures pack and your config it can take a while to fully load in RAM.

**Comment by twoprimehydroxyl** [comment]
Awesome. Thanks!
