### ISSUE TITLE
[Dolphin] Left analog as a new Wiimote IR Mode

### ISSUE THREAD

**Issue by bloomorte** [libretro/dolphin#283]
As mentioned here https://github.com/libretro/dolphin/pull/281

The "Left Stick" was added as a new "Wiimote IR Mode" option
I think this was unintentional, but If you use "Right Stick" as IR mode, the left stick is also acting as a tilt motion with "Wiimote + Nunchuk" device type. 

The issue here is that if you're using an Xbox Controller, for example, you can't use both analogs at the same time.
In Super Mario Galaxy, for example, you should be able to walk with the left analog while using the right analog to collect star bits.

In this current version, If you move the left stick, the cursor of the wiimote (which is assigned to the right analog) imediatelly disappears. Also, Mario keeps spinning all the time when just walking (which uses nunchuk analog).

**Comment by bslenul** [comment]
Reverted yesterday (#284), this can be closed ;)

**Comment by bloomorte** [comment]
Fixed, thank you so much!
