### ISSUE TITLE
Dolphin core "Max Anisotropy" option doesn't work.

### ISSUE THREAD

**Issue by AlanRibas** [libretro/dolphin#292]
I recently set up the core of Nintendo Wii (Dolphin) in RetroArch.
But I found a problem.
The option called "Max Anisotropy" doesn't seem to work.

I took two pictures of Mario's head (as shown in the attached photos), on that first player number selection screen.The 1st photo I put at the maximum of the "Max Anisotropy" field (16x); and in the 2nd photo I put it to a minimum (1x). There was no change. No matter what value I choose in the "Max Anisotropy" field, nothing happens. I already saved the settings, closed RetroArch and entered again. But nothing worked.  In the Dolphin emulator (stand alone), all jaggies disappeared, leaving the image very beautiful. 

Can someone help me?

![2](https://user-images.githubusercontent.com/16063712/204913133-d1f0722f-33ff-45d5-b262-41d5fae17b42.jpg)
![1](https://user-images.githubusercontent.com/16063712/204913164-80442c92-b7d1-4698-a492-3137d148e812.jpg)
![3](https://user-images.githubusercontent.com/16063712/204913288-68961903-bbcc-47be-b599-5db84523c5fa.jpg)

**Comment by nightsy** [comment]
> I recently set up the core of Nintendo Wii (Dolphin) in RetroArch. But I found a problem. The option called "Max Anisotropy" doesn't seem to work.
> 
> I took two pictures of Mario's head (as shown in the attached photos), on that first player number selection screen.The 1st photo I put at the maximum of the "Max Anisotropy" field (16x); and in the 2nd photo I put it to a minimum (1x). There was no change. No matter what value I choose in the "Max Anisotropy" field, nothing happens. I already saved the settings, closed RetroArch and entered again. But nothing worked. In the Dolphin emulator (stand alone), all jaggies disappeared, leaving the image very beautiful.
> 
> Can someone help me?
> 
> ![2](https://user-images.githubusercontent.com/16063712/204913133-d1f0722f-33ff-45d5-b262-41d5fae17b42.jpg) ![1](https://user-images.githubusercontent.com/16063712/204913164-80442c92-b7d1-4698-a492-3137d148e812.jpg) ![3](https://user-images.githubusercontent.com/16063712/204913288-68961903-bbcc-47be-b599-5db84523c5fa.jpg)

Hello Alan how are you? I'm contacting you because I saw that you had a problem with emulation a while ago, where the games were not reading, at the moment I'm having the same problem as you. Can you tell me if you managed to solve the problem with the emulators? Or really had to format the PC?

you posted in this thread:
https://github.com/libretro/RetroArch/issues/13627

**Comment by bslenul** [comment]
You're mistaking anisotropic filtering with anti-aliasing: https://en.wikipedia.org/wiki/Anisotropic_filtering

That being said, I just submitted a PR to add an anti-aliasing option ;)

**Comment by AlanRibas** [comment]
> > I recently set up the core of Nintendo Wii (Dolphin) in RetroArch. But I found a problem. The option called "Max Anisotropy" doesn't seem to work.
> > I took two pictures of Mario's head (as shown in the attached photos), on that first player number selection screen.The 1st photo I put at the maximum of the "Max Anisotropy" field (16x); and in the 2nd photo I put it to a minimum (1x). There was no change. No matter what value I choose in the "Max Anisotropy" field, nothing happens. I already saved the settings, closed RetroArch and entered again. But nothing worked. In the Dolphin emulator (stand alone), all jaggies disappeared, leaving the image very beautiful.
> > Can someone help me?
> > ![2](https://user-images.githubusercontent.com/16063712/204913133-d1f0722f-33ff-45d5-b262-41d5fae17b42.jpg) ![1](https://user-images.githubusercontent.com/16063712/204913164-80442c92-b7d1-4698-a492-3137d148e812.jpg) ![3](https://user-images.githubusercontent.com/16063712/204913288-68961903-bbcc-47be-b599-5db84523c5fa.jpg)
> 
> Hello Alan how are you? I'm contacting you because I saw that you had a problem with emulation a while ago, where the games were not reading, at the moment I'm having the same problem as you. Can you tell me if you managed to solve the problem with the emulators? Or really had to format the PC?
> 
> you posted in this thread: [libretro/RetroArch#13627](https://github.com/libretro/RetroArch/issues/13627)

I managed to solve the problem without formatting my computer.
The whole point was that my computer in its video settings was configured to run at a maximum of 30 fps. I do not know how this happened. I must have unintentionally ticked that option.

**Comment by AlanRibas** [comment]
> You're mistaking anisotropic filtering with anti-aliasing: https://en.wikipedia.org/wiki/Anisotropic_filtering
> 
> That being said, I just submitted a PR to add an anti-aliasing option ;)

Thanks a lot for the help. They really are different things.

**Comment by bslenul** [comment]
No problem! The "Anti-Aliasing" core option was added, should be available from the online updater in a few hours.
