### ISSUE TITLE
Suggestion for controller timeout

### ISSUE THREAD

**Issue by sonninnos** [libretro/dolphin#298]
Apparently Dolphin has a built-in controller timeout, which can be disabled by adding
```
Options/Always Connected = True
```
To `User/Config/GCPadNew.ini` inside the `[GCPadx]` controller blocks.

I found this option in the standalone, and the fix addition was confirmed by the user who reported it, and since it seems to be the cleanest way of achieving it, I think it ought to be the default in the core.

Then again if the files are generated only when they don't exist, it won't apply to existing installations..

**Comment by bslenul** [comment]
Done, looks like there's no equivalent option for when emulating Wiimote tho.
