### ISSUE TITLE
building dolphin dll with msvc 2017 results in slow performance

### ISSUE THREAD

**Issue by RetroSven** [libretro/dolphin#34]
I must be missing something - the DLL compiles fine in debug and release mode, but both the release and debug DLLs result in much slower performance than the official DLL that gets downloaded into RA from online.  Can someone shed some light on what settings I need to tweak in MSVC in order to produce a build that is the same as the official?

(It's not a RA config that's the problem - if I just swap out the DLL with the official one, everything is fine)

Thanks

**Comment by RetroSven** [comment]
nm - found it

**Comment by inactive123** [comment]
interesting, so what turned out to be the issue?

**Comment by RetroSven** [comment]
https://yarn.co/yarn-clip/fd21f95d-98fb-4658-a8aa-143ddb382b74

I mucked the debug/release DLLs - was actually using debug when I thought I was using release :P
