### ISSUE TITLE
Cannot boot games win10

### ISSUE THREAD

**Issue by TobyKaos** [libretro/dolphin#46]
Since a few day I want to launch games but crash on startup on win10. I try with a fresh install of retroarch.
logs attached
[log.txt](https://github.com/libretro/dolphin/files/2423129/log.txt)

**Comment by Papermanzero** [comment]
Tried it and it is working without issues. Have you used the documentation to set up dolphin correctly?
https://docs.libretro.com/library/dolphin/

**Comment by TobyKaos** [comment]
Hoo, I read the doc and do it , and ... it works. Sorry. I have Dolphin emu install on my pc and maybe I am confusing brtween two.

**Comment by Papermanzero** [comment]
Then we can close the issue ;)
