### ISSUE TITLE
Resident Evil 2 music broken

### ISSUE THREAD

**Issue by aboutafter** [libretro/dolphin#55]
Resident Evil 2 (and I think 3) has a long standing bug where the music is broken: https://bugs.dolphin-emu.org/issues/9840

As far as I know the only way to fix it is with some kind of hack. Is this something that can be fixed on the libretro core?

**Comment by ToniBC** [comment]
Indeed the music sounds bad, since version 5.0-13452 this error was patched, but it seems that the Libretro version is not updated or that patch was not applied.

**Comment by ToniBC** [comment]
Testing with version 4ffaf05, updating the sys folder, the error is still present. It may be that the fix is not yet applied in this version.

The same game in Dolphin Standalone works without problems.
