### ISSUE TITLE
Starting dolphin for the first time leads to a segfault

### ISSUE THREAD

**Issue by i30817** [libretro/dolphin#68]
I have the 'Sys' dir of upstream dolphin and i'm using and i noticed this on latest core from the online updater, but debuged it from a debug build of the core self built from libretro-super. Sadly the backtrace is useless
```

i30817@AIVAS:~/.config/retroarch/cores$ md5sum dolphin_libretro.so 
d9232d5bd049832fb03674449c4f5028  dolphin_libretro.so

```
(the core information doesn't have a revision for the core sadly).

When the dolphin core loads a game for the first time, it creates a file structure on the Retroarch save dir : `/home/i30817/.config/retroarch/saves/User`

Trying to start a game (any game, GC or Wii) on this state appears to freeze the game on the first frame. This is often a black screen, but in instance for 'Resident Evil 2' you can barely see the 'this game contains scenes of explicit violence and gore' starting to fade in. 

Retrying lets you continue on, but it would be nice if this worked.

 
I built the core and retroarch with libretro super as mentioned, in debug mode.

I had to comment a debug assert in the code that was useless (it checked if 'it succeed creating a dir' and failed always because it tried to 'create' /tmp and always failed because that's already there).

After that sadly the bt for the real bug goes nowhere:
```

...
[libretro INFO] 29:29:629 Core/Boot/Boot.cpp:328 N[BOOT]: Booting from disc: /media/i30817/Games/Nintendo Gamecube+Wii/Eternal Darkness.iso
[Thread 0x7fffc8d6e700 (LWP 16427) exited]
[New Thread 0x7fffc8d6e700 (LWP 16428)]
[libretro INFO] 29:29:630 Core/Boot/Boot_BS2Emu.cpp:205 I[BOOT]: Faking GC BS2...
[New Thread 0x7fffb0e7d700 (LWP 16429)]

Thread 13 "CPU thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb0e7d700 (LWP 16429)]
0x00007fff94fb8e70 in ?? ()
(gdb) bt
#0  0x00007fff94fb8e70 in  ()
#1  0x0000000000000000 in  ()
(gdb) 

```
I built the core with 
mkdir build; cd build
cmake .. -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build . --target dolphin_libretro --config Debug

Is there some kind of extra thing i need to do or is that super short stacktrace a symptom of a JIT screwing up?

From this response: https://stackoverflow.com/a/121512/214260

this type of trace seems to indicate that the thread died without executing anything significant (to have literally no user code running). Basically there is something wrong after '[libretro INFO] 29:29:630 Core/Boot/Boot_BS2Emu.cpp:205 I[BOOT]: Faking GC BS2...'. It makes the files it needs but then crashes right at the exit, which, yeah, we basically knew that.

**Comment by i30817** [comment]
This is admittedly strange.

It seems that the thread that is supposed to "Faking GC BS2..." always segfaults, but only the first time it prevents the core from continuing. If you retry it with a non-debug build, it goes on. If you try it (after the dirs are created) with a debug build (after commenting line 198 at  Source/Core/Core/IOS/FS/HostBackend/FS.cpp  which is a debug assert that always triggers on debug builds, but not Release), it crashes with the debug strack trace on the previous post.

This (IMO) seems to indicate that the thread always crashes but only takes down the non-debug build the first time because of a race. But on the debug build, it *will* crash (even if you comment the bogus assert that was failing because it couldn't create '/tmp/' :rolleyes:)

**Comment by flyinghead** [comment]
I have noticed this as well. There's a deadlock when creating the User directory for the first time.

The segfault is misleading because dolphin uses SIGSEGV when the Fast Mem option is on (which is the default). So these segfaults are expected and are not an error.

**Comment by i30817** [comment]
ahhhh, I was wondering why it seemed to freeze and not crash on release. Good to know.

**Comment by i30817** [comment]
Seems fixed.
