### ISSUE TITLE
Unable to press 'R' and 'L' gamecube buttons in keyboard mapping now

### ISSUE THREAD

**Issue by i30817** [libretro/dolphin#69]
This is (probably) a regression from https://github.com/libretro/dolphin/pull/61 which changes the 'L' and 'R' gamecube controller buttons to map to 'L2' and 'R2' which are the retropad analogic buttons.

~~Apparently from some testing in eternal darkness, those analog buttons when mapped to the keyboard get only 'half pressed' on a tap or a hold.~~

~~I know of this because i can no longer run (hold 'L' or keyboard 'q' in my case), move inside the inventory menu to another tab (tap 'L' or 'R') but i can still reload a gun if it's not full (press or tap 'R').~~

edit: turns out from the image that retropad 'R' is bound to gamecube controller 'Z', retropad 'L' is bound to nothing, and retropad L2 (keyboard 'e') and R2 (keyboard 'r') are bound to 'L' and and 'R'.

They still don't work in game (pressing 'e' and 'r' do nothing on those situations that required them in _Eternal Darkness_, running and menu tab change), but i can no longer think that 'pressing 'w' working to reload the gun means that it's a case of analog retropad being 'half pressed', because that button was actually gamecube 'Z'.

Resuming analog retropad buttons mapped to a digital event like keyboard key appear to not be depressed (fully or not) when pressed on a keyboard. It's good to be able to map these analog retropad buttons to the actual analog buttons on the gamecube mapping if you're using a real controller with analog triggers, but i wish retropad had special handling to simulate a 'fully pressed button' if the hardware binding is digital like a keyboard key.

here is a image of the running core input menu showing the affected bindings:

![screenshot from 2019-01-05 10-48-45](https://user-images.githubusercontent.com/757900/50723644-61b8eb80-10d8-11e9-9471-8d12bcf23afc.png)

I don't really understand what the 'User 1: N/A' underneath the selected binding means.

https://commons.wikimedia.org/wiki/File:GCController_Layout.svg

**Comment by flyinghead** [comment]
This should be fixed now

**Comment by i30817** [comment]
yes, it's fixed.
