### ISSUE TITLE
Dolphin core doesn't always pause in the menu correctly, atleast in Super Mario Sunshine!

### ISSUE THREAD

**Issue by anyputer** [libretro/dolphin#7]
The Dolphin core doesn't always pause correctly in the menu, atleast in Super Mario Sunshine!
With that I mean either the music keeps playing in the menu or it properly pauses in the menu during prerendered cutscenes.

**Comment by anyputer** [comment]
And now the problem is even worse: #8

**Comment by ghost** [comment]
How are you able to play the game at all? As far as I can work out, the Dolphin core doesn't support the 2-stage triggers that are required for this game.

**Comment by anyputer** [comment]
This issue is fixed in the new Dolphin core too!
