### ISSUE TITLE
Support for custom textures like in Dolphin?

### ISSUE THREAD

**Issue by sondregronas** [libretro/dolphin#74]
Hey! Would it be possible to implement the "Load custom textures" feature from Dolphin to libretro? By default they are loaded from:  `C:\Users\USER\Documents\Dolphin Emulator\Load\Textures\GAME_ID` - I presume this might be a simple fix? (With custom folder path)

It's by default under Dolphin Emulator/Config/GFX.ini
```
[Settings]
CacheHiresTextures = True
HiresTextures = True
```

**Comment by flyinghead** [comment]
There's a new core option to load custom textures. It works the same as with standalone Dolphin

**Comment by sondregronas** [comment]
Awesome!
