### ISSUE TITLE
no widescreen

### ISSUE THREAD

**Issue by legluondunet** [libretro/dolphin#84]
Hello,
Gamecube and WII games that support widescreen are only showed in 4:3, **even if I enabled widescreen option**.
I verified in Dolphin main program, it works, but not with the Dolphin Retroarch core.

Here a test with Angry Birds game:
Dolphin main program:
![capture d ecran de 2019-02-11 10-24-23](https://user-images.githubusercontent.com/325405/52561150-d2030d00-2dfa-11e9-9c35-bc4d20d7a3c6.png)

Dolphin Libretro core:
![capture d ecran de 2019-02-11 10-23-59](https://user-images.githubusercontent.com/325405/52561125-c0ba0080-2dfa-11e9-82df-d7e446ebbddc.png)

Thank you for your help.

**Comment by QuaiGoner** [comment]
Same issue here.
Latest nightly build
Windows 10 x64

**Comment by drcouzelis** [comment]
I was personally able to resolve this by changing the following setting:

Settings -> Video -> Aspect Ratio to "Core provided"

Does that fix it for you?

**Comment by legluondunet** [comment]
this setting "Settings -> Video -> Aspect Ratio to "Core provided" resolved the issue. Thank you @drcouzelis
