### ISSUE TITLE
Stick sensitivity (Xbox 360 Controller)

### ISSUE THREAD

**Issue by dukeblooders** [libretro/dolphin#91]
Hello,

I'm using a Xbox 360 controller, but even when I don't use the stick, the core detects an input.
It happens on every games and I don't have this issue with other cores (N64, PSP, ,..).

Is it possible to add an option to change the stick sensitivity (or is it deadzone) ?

Thanks

**Comment by ghost** [comment]
Just FYI the latest nightly of RetroArch now has a global setting for this that works on all cores.

**Comment by dukeblooders** [comment]
Nice, I will test it. Thanks

**Comment by dukeblooders** [comment]
I tried the global settings but unfortunately, when I change for the dolphin core, I've get a lack a sensitivity on the other cores.

I also tried a Xbox One controller, it solves the deadzone issue but not the sensitivity (still too high).

**Comment by ghost** [comment]
>I tried the global settings but unfortunately, when I change for the dolphin core, I've get a lack a sensitivity on the other cores.

You just need to create a per-core override so that the setting is only applied for that core.

>I also tried a Xbox One controller, it solves the deadzone issue but not the sensitivity (still too high).

I tested with an xbox one controller, and lowering the sensitivity to below 1.0 solved it for me (I'm using 0.5).

**Comment by dukeblooders** [comment]
Thanks, the core override does the job.

It seems I have to let down the 360 controller for the dolphin core unless there's a way to fix that somehow by code. I'm not even sure it's an issue with mine or with every 360 controller.

**Comment by dukeblooders** [comment]
I didn't notice immediately, but if I reduce the global sensitivity (to 0.9 for example), the triggers don't work anymore (on both controllers). They are analog too if I'm not mistaken. I have tested on Mario Kart DD and NHL04.

**Comment by ghost** [comment]
Hmm, that one sounds like your "Input Button Axis Threshold" could be set too high. The default is 0.5, meaning for games that use digital buttons which you've mapped to an analog one, you must press it at least halfway for it to register as a digital button press.

**Comment by dukeblooders** [comment]
I made another few tests : 
- Sensitivity 1.0, Deadzone 0.0, Input Button Axis Threshold : 0.5 (default config)
Everything works fine except sensitivity is too high

- Sensitivity **0.9 (or less)**, Deadzone 0.0, Input Button Axis Threshold : 0.5
Triggers don't work

- Sensitivity **0.9 (or less)**, Deadzone 0.0, Input Button Axis Threshold : **1.0** (or less than 0.5)
Triggers don't work

- Sensitivity **0.9 (or less)**, Deadzone **0.1**, Input Button Axis Threshold : 0.5
Triggers don't work

- Sensitivity **0.9 (or less)**, Deadzone **1.0**, Input Button Axis Threshold : 0.5
Weird case, triggers work but of course, sticks don't

**Comment by dukeblooders** [comment]
I saw that you did implement a fix for the analog buttons on the RetroArch repository @bparker06 .

Everything works fine now. Thank you very much !
