### ISSUE TITLE
.m3u support

### ISSUE THREAD

**Issue by dukeblooders** [libretro/dolphin#97]
Unless I'm mistaken, the core doesn't support .m3u files.
Depending the frontend (in my case ES), it's the only way to have a single entry for a multidiscs game.

Could it be possible to add it (like Reicast or Bettle PSX) ?

**Comment by Papermanzero** [comment]
Have the same issue. I have m3u files but dolphin will not boot

**Comment by Papermanzero** [comment]
Any update? Multi disc become unplayable :(

**Comment by whocares0101** [comment]
This is a must have feature.

**Comment by Papermanzero** [comment]
Now with the automatic disc change it would be a cool feature. Defining multidisc games in the m3u and let dolphin switch the discs automatically

**Comment by dukeblooders** [comment]
@psychonic
Hi, I saw your PR for this issue. Thanks, that's awesome !
I hope, it will be in stable/nightly soon.

Any chance you can take a look at https://github.com/libretro/dolphin/issues/105 ? 
RE:CV works now, but there are still PAL games that don't launch.
